### ISSUE TITLE
running shoes bug?

### ISSUE THREAD

**Issue by Clinkr1000** [KenyMylankca/EnhancedArmaments#19]
[crashlohg.txt](https://github.com/KenyMylankca/EnhancedArmaments/files/2847447/crashlohg.txt)

**Comment by Clinkr1000** [comment]
i dont know what mod added running shoes, a red set of shoes. but whejnever i hover over it the game crashes.

**Comment by KenyMylankca** [comment]
then add the crashing items into the blacklist in config. it is there for that.

**Comment by Clinkr1000** [comment]
how? all i know is the display name

**Comment by KenyMylankca** [comment]
press f3+H then you will see its full mod:item_name. write it into the blacklist config.
for example: **forestry:knife** (example)

**Comment by Clinkr1000** [comment]
without hovering with mouse? because that causes crash... i can equip it, but the item tooltip causes it to crash

**Comment by Clinkr1000** [comment]
i wil try it.

**Comment by Clinkr1000** [comment]
is there a way to unequip items without using gui? because the instant my mouse hovers over the item in a way that would normally show tooltip the game crashes.

**Comment by Clinkr1000** [comment]
not working.
i cant even blacklist the item because i dont know its id.

this error is the problem.

	[10:41:11] [Client thread/ERROR]: Exception caught during firing event net.minecraftforge.event.entity.player.ItemTooltipEvent@8a893f2:
	java.lang.ArrayIndexOutOfBoundsException: 0
		at com.jannesoon.enhancedarmaments.event.EventItemTooltip.changeTooltips(EventItemTooltip.java:128) ~[EventItemTooltip.class:?]
		at com.jannesoon.enhancedarmaments.event.EventItemTooltip.addInformation(EventItemTooltip.java:62) ~[EventItemTooltip.class:?]
		at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_436_EventItemTooltip_addInformation_ItemTooltipEvent.invoke(.dynamic) ~[?:?]
		at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
		at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
		at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:335) [ForgeEventFactory.class:?]
		at net.minecraft.item.ItemStack.getTooltip(ItemStack.java:889) [aip.class:?]
		at net.minecraft.client.gui.GuiScreen.getItemToolTip(GuiScreen.java:143) [blk.class:?]
		at net.minecraft.client.gui.GuiScreen.renderToolTip(GuiScreen.java:137) [blk.class:?]
		at net.minecraft.client.gui.inventory.GuiContainerCreative.renderToolTip(GuiContainerCreative.java:737) [bmp.class:?]
		at net.minecraft.client.gui.inventory.GuiContainer.renderHoveredToolTip(GuiContainer.java:175) [bmg.class:?]
		at net.minecraft.client.gui.inventory.GuiContainerCreative.drawScreen(GuiContainerCreative.java:684) [bmp.class:?]
		at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396) [ForgeHooksClient.class:?]
		at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1124) [buq.class:?]
		at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119) [bib.class:?]
		at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
		at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
		at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
		at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
		at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by KenyMylankca** [comment]
> without hovering with mouse? because that causes crash... i can equip it, but the item tooltip causes it to crash

remove Enhanced Armaments, then hover over it to see what is it.
