### ISSUE TITLE
Crash using minecraft bow

### ISSUE THREAD

**Issue by MEATacc** [KenyMylankca/EnhancedArmaments#3]
Hi,
No problems leveling up minecraft swords but I tried using a vanilla bow in my mod pack and the game crashes as soon as the arrow hits a mob.

Im nor sure if its a conflict with another mod or other, I couldn't tell... but I've attached the log files bellow for you and here is a quick snippet of the crash: 

---- Minecraft Crash Report ----

Description: Ticking entity

java.lang.ArrayIndexOutOfBoundsException: 0
    at com.jannesoon.enhancedarmaments.event.EventLivingHurt.useRarity(EventLivingHurt.java:157)
    at com.jannesoon.enhancedarmaments.event.EventLivingHurt.onHurt(EventLivingHurt.java:66)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1169_EventLivingHurt_onHurt_LivingHurtEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:590)
    at net.minecraft.entity.EntityLivingBase.damageEntity(EntityLivingBase.java:1401)
    at net.minecraft.entity.EntityLivingBase.attackEntityFrom(EntityLivingBase.java:917)
    at net.minecraft.entity.monster.EntityMob.attackEntityFrom(EntityMob.java:70)
    at net.minecraft.entity.projectile.EntityArrow.onHit(EntityArrow.java:369)
    at net.minecraft.entity.projectile.EntityArrow.onUpdate(EntityArrow.java:267)
    at net.minecraft.entity.projectile.EntityTippedArrow.onUpdate(SourceFile:98)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1990)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1952)
    at net.minecraft.world.World.redirect$updateEntity$zbb000(World.java:4114)
    at net.minecraft.world.World.updateEntities(World.java:1756)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)

[crash-2018-07-28_08.11.27-server.txt](https://github.com/JanneSoon/EnhancedArmaments/files/2237730/crash-2018-07-28_08.11.27-server.txt)

[latest.log](https://github.com/JanneSoon/EnhancedArmaments/files/2237731/latest.log)

Thanks for looking into this!

**Comment by KenyMylankca** [comment]
did you have any abilities in your bow?

**Comment by JanneSoon** [comment]
and did it happen again?

**Comment by KenyMylankca** [comment]
ok i got it. will be fixed soon.

**Comment by MEATacc** [comment]
Thanks! 
To answer your question, it happens on any bow without abilities. And every time I tried to use it.

**Comment by vibes81** [comment]
Also happens with "modded" bows IE silent gear, my crash report is below

https://paste.dimdev.org/gukafixebi.mccrash

**Comment by KenyMylankca** [comment]
> Also happens with "modded" bows IE silent gear, my crash report is below
> 
> https://paste.dimdev.org/gukafixebi.mccrash
This crash is about the Silent Gear mod. The bows in Silent Gear have the "When in main hand:" tooltip, which shouldn't have. Ranged weapons (like vanilla bow) cannot have "When in main hand:" tooltip. So please report it to the author of Silent Gear.

**Comment by KenyMylankca** [comment]
> Also happens with "modded" bows IE silent gear, my crash report is below
> 
> https://paste.dimdev.org/gukafixebi.mccrash

This crash is about the Silent Gear mod. The bows in Silent Gear have the "When in main hand:" tooltip, which shouldn't have. Ranged weapons (like vanilla bow) cannot have "When in main hand:" tooltip. So please report it to the author of Silent Gear.
But however, i fixed this too, to make my mod much more improved.
